#!/bin/sh
# ambros:
# control script for one channel

if test "$1" = ""
then cat <<EOT
usage: $0 <configfile>

start AMBROS control instance configured by <configfile>
EOT
exit 1
fi

# save directories of scripts and instance ("root", configuration file)
# is somewhat complicated to correctly handle relative paths
# (not using $OLDPWD etc to keep better portability)
owd=`pwd`
cd `dirname $0`
SCRIPTDIR=`pwd`
echo SCRIPTDIR: $SCRIPTDIR >&2
cd "$owd"
cd `dirname $1`
ROOTDIR=`pwd`
echo ROOTDIR: $ROOTDIR >&2
AMBROSCONFIG=`basename $1`

cd $SCRIPTDIR || { echo "cannot access scripts in $SCRIPTDIR" ; exit 3 ; }
# read global settings
. ./constants.sh
logf=`logfile ambros`
# (re)generate morse code table
cd morse && ./chargen.sh

# create temporary directory, ignore error if already existing
mkdir $TMPDIR 2>/dev/null
if test ! -d $TMPDIR
then
 logit $logf init "cannot create temporary directory $TMPDIR - aborting!"
 exit 3
fi
logit $logf init tempdir $TMPDIR

if test ! -d "$ROOTDIR" -o ! -x "$ROOTDIR" -o ! -r "$ROOTDIR" -o ! -w "$ROOTDIR"
then
 logit $logf init "base directory ($ROOTDIR) is not usable - aborting!"
 exit 2
fi

# get channel list
cd "$ROOTDIR"
logit $logf init working in base directory $ROOTDIR
lchannels=`configread $AMBROSCONFIG CHANNELS '.,:;/'`
logit $logf channels list: $lchannels

# collect channel directory names
unset channels
for ch in $lchannels
do
if test -d $ch -a -x $ch -a -r $ch -a -w $ch
then channels="$ch $channels"
else
 logit $logf channels "$ch is not read/write/accessible directory, ignoring!"
fi
done

GLOBALSPEED=`configread $AMBROSCONFIG WPM`
GLOBALSPEED=${GLOBALSPEED:-12}
logit $logf init "global speed $GLOBALSPEED Words/min"

cd "$ROOTDIR"
if test ! -d "$SOURCEDIR" -o ! -x "$SOURCEDIR" -o ! -r "$SOURCEDIR" -o ! -w "$SOURCEDIR"
then
 logit $logf init "source directory ($ROOTDIR/$SOURCEDIR) is unusable - aborting!"
 exit 2
fi

# handler for aborting
finish () {
 logit $logf finish "received abort signal, stopping all subprocesses"
# if no PID is set, use 1 (init) as a dummy argument
 /bin/kill -TERM ${pidassembler:-1} $pidchannelchief
 logit $logf finish "signalling main control loop"
 AMBROSABORT=1
}
AMBROSABORT=0
 
trap finish INT TERM STOP

logit $logf init "entering main control loop, PID $$"

tmpf=$TMPDIR/ambros$$.tmp

# for communication with extractor
extractorfile=$TMPDIR/$EXTRACTORFILE

while test $AMBROSABORT -eq 0
do
logit $logf mainloop passing

# collect source names
for ch in $channels
do
csources=`configread "$ch/$CHANNELCONFIG" SOURCES '.,:;/'`
lsources="$csources $lsources"
done
cd $ROOTDIR/$SOURCEDIR
{
 for ls in $lsources
 do echo $ls
 done
} | sort -r | uniq | {
 while read sc
 do
 if test -d "$sc" -a -x "$sc" -a -r "$sc" -a -w "$sc"
 then echo $sc
 fi
 done
} > $tmpf
sources=`cat $tmpf`
logit $logf mainloop "valid sources: $sources"

# fetch and process sources ('_' for channel prefix, i.e 'all' for sources)
SCRIPTDIR="$SCRIPTDIR" $SCRIPTDIR/extractor _ $extractorfile $sources

# start&control `assembler`
# start&control `channelchief`

echo
echo enter q to abort:
read ans
if test "$ans" = "q"
then AMBROSABORT=99
fi

done

# remove all temporary stuff
#rm -rf $TMPDIR

logit $logf ambros finished.
