#!/bin/sh
# extractor <prefix> <source1> <source2> ...
# must be run in directory of sources
# will process each source according to its configuration file
# and save new clean text (if available) in same directory
# with <prefix> as start of name

# read global settings
. $SCRIPTDIR/constants.sh

minpoll=$MAXPOLLING
starttime=`nowsec`
echo : starttime $starttime

echo $0 working:

prefix=$1
shift

for source in $*
do echo :$source
 cd $source
# ignore directories without readable configuration file
 if test -r $SOURCECONFIG
 then
# read status values (or set start values)
  if test -r $SOURCESTATUS
  then
   index=`configread $SOURCESTATUS INDEX`
   lasthash=`configread $SOURCESTATUS LASTHASH`
   lastpoll=`configread $SOURCESTATUS LASTPOLL`
  else
   index=$SOURCEINDEXSTART
   lasthash=nil
   lastpoll=0
  fi
# calculate time of next polling
  polling=`configread $SOURCECONFIG POLLING`
  now=`nowsec`
  polling=`expr $lastpoll + $polling - $now`
# poll if passed
  if test $polling -le 0
  then
   echo : now polling $source
   
# re-read polling interval
   polling=`configread $SOURCECONFIG POLLING`
  fi
# calculate minimal future polling time
  if test $minpoll -lt $polling
  then minpoll=$polling
  fi
# save current status
  cat <<EOT >$SOURCESTATUS
INDEX		$index
LASTHASH	$lasthash
LASTPOLL	$now
EOT
 else echo : no configfile for $source found, ignoring
 fi
 cd ..
done

# save closest next polling time for controller
echo : minpoll=$minpoll
echo NEXTPOLL `expr $starttime + $minpoll` > $NEXTPOLLCONFIG
