#!/bin/sh
# fetcher:
# get text contents from sources, return creation/modification time
# and source description together with text through stdout
# (non-zero exit code in case of error)

. `dirname $0`/constants.sh

proto=${1%%://*}
src="${1#*://}"
gen=-1
tmpf=${TMP:-/tmp}/fetcher-$proto-$$.tmp
logf=${TMP:-/tmp}/fetcher-wget-`date +%y%U`.log
#echo ::$tmpf::

case $proto in
file)
 gen=`ls -l --time-style=+%s "$src" | { read _ _ _ _ _ t _ ; echo $t ; }`
 cat "$src" >$tmpf
 ;;
http|https|ftp)
 wget -a $logf -O $tmpf -T 60 "$proto://$src" && gen=`date +%s`
 ;;
gopher)
 ;;
rss)
 ;;
*) gen=-1 ;;
esac

echo $PBLSRC $proto://$src
echo $PBLGEN $gen
echo
if test $gen -gt 0
then
 cat $tmpf
 gen=0
else gen=1
fi

rm -f $tmpf
exit $gen
