#!/bin/sh
# fetcher:
# get text contents from sources, return creation/modification time
# and source description together with text through stdout
# (non-zero exit code in case of error)

. `dirname $0`/constants.sh

# parse protocol and source from argument
proto=${1%%://*}
src="${1#*://}"

# genesis time, less than 0 means failure
gen=-1

# temporary and log file
tmpf=$TMPDIR/fetcher-$proto-$$.tmp
logf=$TMPDIR/fetcher-log-`date +%y%U`.log
#echo ::$tmpf::

# timeout for total script is 3 times that for fetch operation
timeout=`expr $FETCHTIMEOUT '*' 3`

logit () { echo : "$@" >>$logf ; }

cat <<EOT >>$logf

# fetcher at `date`

EOT

case $proto in
file)
 statstat=`stat --help 2>&1|head -n 1`
 case $statstat in
 Usage*) gen=`stat -c %Y "$src"` ;;
 "stat: unknown option"*) gen=`stat -f %a "$src"` ;;
 *) gen=`date +%s` ;;
 esac
 cat "$src" >$tmpf
 logit getting file: $src ...
 ;;
http|https|ftp)
 logit wget ...
 wget -a $logf -O $tmpf -T $FETCHTIMEOUT "$proto://$src" && gen=`date +%s`
 ;;
gopher)
 ;;
rss)
 ;;
*) gen=-1 ;;
esac

echo SOURCE $proto://$src
echo GENESIS $gen
echo
if test $gen -gt 0
then
 cat $tmpf
 gen=0
 logit ok
else
 gen=1
 logit FAILED
fi

rm -f $tmpf
exit $gen
