#!/bin/sh
# planner:
# assemble transmission texts from clean texts
# arg1=channel
# environment variables ROOTDIR and SCRIPTDIR must be defined by caller,
# and script must be called from channel directory as working directory

. $SCRIPTDIR/constants.sh

# save channel name for reference - but we should already be in that directory
chan=${1:UNKNOWN}

myself=planner-$chan
logf=`logfile $myself`
statf=$STATUSDIR/$myself

statrep $statf STATUS initializing

# check if config file present, if not, sleep to reduce load
if ! -r $CHANNELCONFIG
then
 logit $logf FAIL missing config file $CHANNELCONFIG
 statrep $statf STATUS FAIL missing config file $CHANNELCONFIG
 sleep 10
 return 1
fi

# check if prefix defined -- we cannot define it here by ourselves!
if ! prefix=`configread $CHANNELCONFIG PREFIX`
then
 logit $logf FAIL missing PREFIX definition in $CHANNELCONFIG
 statrep $statf STATUS FAIL missing PREFIX definition in $CHANNELCONFIG
 sleep 10
 return 1
fi

# handler for restarting/reloading
restart () {
 logit $logf signal "(re)loading config, (re)starting"
 RESTARTPLANNER=1
}
# flag initially _set_ to force initializing during launch
# will be reset after initialization routine
RESTARTPLANNER=1
trap restart $SIGDAEMONRESTART

# handler for stopping
finish () {
 logit $logf signal finishing
 ABORTPLANNER=1
}
ABORTPLANNER=0
trap finish $SIGDAEMONTERMINATE

while test ABORTPLANNER -eq 0
# reduce load in case of severe bugs/problems
do sleep 1
if test $RESTARTPLANNER -eq 1
then
 sources=`configread $CHANNELCONFIG SOURCES ',:;'`
 logit $logf config "sources: $sources"
# last resource default: no postprocessor, i.e `cat`
 postprocessor=`configread $CHANNELCONFIG POSTPROCESSOR`
 postprocessor=${postprocessor:-/bin/cat}
 logit $logf config "postprocessor: $postprocessor"
# desperate defaults: ToC length 2min, ToC period 5 slices
 toclength=`configread $CHANNELCONFIG TOCLENGTH`
 toclength=${toclength:-120}
 tocslices=`configread $CHANNELCONFIG TOCSLICES`
 tocslices=${tocslices:-5}
# do not restart until signal received again
 RESTARTPLANNER=0
fi

done